export default [
  {
    adult: false,
    backdrop_path: "/kdbLf3aTQsEXqYlH9vA4fzmnSFz.jpg",
    genre_ids: [10752, 18, 28],
    id: 228150,
    original_language: "en",
    original_title: "Fury",
    overview:
      "In the last months of World War II, as the Allies make their final push in the European theatre, a battle-hardened U.S. Army sergeant named 'Wardaddy' commands a Sherman tank called 'Fury' and its five-man crew on a deadly mission behind enemy lines. Outnumbered and outgunned, Wardaddy and his men face overwhelming odds in their heroic attempts to strike at the heart of Nazi Germany.",
    popularity: 161.934,
    poster_path: "/c5dOrzJiW3jA3Erej6zOgJX8y76.jpg",
    release_date: "2014-10-15",
    title: "Fury",
    video: false,
    vote_average: 7.5,
    vote_count: 10104,
  },
  {
    adult: false,
    backdrop_path: "/ff2ti5DkA9UYLzyqhQfI2kZqEuh.jpg",
    genre_ids: [28, 53],
    id: 245891,
    original_language: "en",
    original_title: "John Wick",
    overview:
      "Ex-hitman John Wick comes out of retirement to track down the gangsters that took everything from him.",
    popularity: 89.116,
    poster_path: "/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg",
    release_date: "2014-10-22",
    title: "John Wick",
    video: false,
    vote_average: 7.4,
    vote_count: 15965,
  },
  {
    adult: false,
    backdrop_path: "/9vAoubhoZE8aSkUZoSfxs3UWZhO.jpg",
    genre_ids: [53, 28, 80],
    id: 156022,
    original_language: "en",
    original_title: "The Equalizer",
    overview:
      "McCall believes he has put his mysterious past behind him and dedicated himself to beginning a new, quiet life. But when he meets Teri, a young girl under the control of ultra-violent Russian gangsters, he can’t stand idly by – he has to help her. Armed with hidden skills that allow him to serve vengeance against anyone who would brutalize the helpless, McCall comes out of his self-imposed retirement and finds his desire for justice reawakened. If someone has a problem, if the odds are stacked against them, if they have nowhere else to turn, McCall will help. He is The Equalizer.",
    popularity: 90.804,
    poster_path: "/9u4yW7yPA0BQ2pv9XwiNzItwvp8.jpg",
    release_date: "2014-09-24",
    title: "The Equalizer",
    video: false,
    vote_average: 7.2,
    vote_count: 7363,
  },
  {
    adult: false,
    backdrop_path: "/nlG452icactoT6hbqECbSEVfGII.jpg",
    genre_ids: [16, 12, 35, 10751, 14],
    id: 228326,
    original_language: "en",
    original_title: "The Book of Life",
    overview:
      "The journey of Manolo, a young man who is torn between fulfilling the expectations of his family and following his heart. Before choosing which path to follow, he embarks on an incredible adventure that spans three fantastical worlds where he must face his greatest fears.",
    popularity: 90.208,
    poster_path: "/aotTZos5KswgCryEzx2rlOjFsm1.jpg",
    release_date: "2014-10-01",
    title: "The Book of Life",
    video: false,
    vote_average: 7.5,
    vote_count: 2221,
  },
  {
    adult: false,
    backdrop_path: "/2gKX53lskaCYk9ycXmaDJKqWiy.jpg",
    genre_ids: [27],
    id: 250546,
    original_language: "en",
    original_title: "Annabelle",
    overview:
      "A couple begins to experience terrifying supernatural occurrences involving a vintage doll shortly after their home is invaded by satanic cultists.",
    popularity: 85.971,
    poster_path: "/a9iL3FIwLrympRyiL5v0tAkwrvX.jpg",
    release_date: "2014-10-02",
    title: "Annabelle",
    video: false,
    vote_average: 5.7,
    vote_count: 5273,
  },
  {
    adult: false,
    backdrop_path: "/x9ezMgOtDPqHatHDvxEG0ILb6Ie.jpg",
    genre_ids: [9648, 53, 18],
    id: 210577,
    original_language: "en",
    original_title: "Gone Girl",
    overview:
      "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.",
    popularity: 64.492,
    poster_path: "/qymaJhucquUwjpb8oiqynMeXnID.jpg",
    release_date: "2014-10-01",
    title: "Gone Girl",
    video: false,
    vote_average: 7.9,
    vote_count: 16051,
  },
  {
    adult: false,
    backdrop_path: "/keEWjA5ykLJo851tIBFdmkxPxxh.jpg",
    genre_ids: [27, 9648],
    id: 270303,
    original_language: "en",
    original_title: "It Follows",
    overview:
      "When carefree teenager Jay sleeps with her older boyfriend for the first time, she learns that she is the latest recipient of a fatal curse that is passed from victim to victim via sexual intercourse. Death, Jay learns, will creep inexorably toward her as either a friend or a stranger. Jay's friends don't believe her seemingly paranoid ravings, until they too begin to see the phantom assassins and band together to help her defend herself.",
    popularity: 73.251,
    poster_path: "/iwnQ1JH1wdWrGYkgWySptJ5284A.jpg",
    release_date: "2014-09-24",
    title: "It Follows",
    video: false,
    vote_average: 6.6,
    vote_count: 5368,
  },
  {
    adult: false,
    backdrop_path: "/isrro0soStk2tSWMsI50lPPhUsU.jpg",
    genre_ids: [80, 18, 9648, 53],
    id: 169917,
    original_language: "en",
    original_title: "A Walk Among the Tombstones",
    overview:
      "Private investigator Matthew Scudder is hired by a drug kingpin to find out who kidnapped and murdered his wife.",
    popularity: 72.651,
    poster_path: "/bQTHTZezSudf27mMQtedHf1XpgO.jpg",
    release_date: "2014-09-18",
    title: "A Walk Among the Tombstones",
    video: false,
    vote_average: 6.3,
    vote_count: 2417,
  },
  {
    adult: false,
    backdrop_path: "/txDX7lBx8bBhF7dRCEfDYmAmdnk.jpg",
    genre_ids: [35, 10749],
    id: 200727,
    original_language: "en",
    original_title: "Love, Rosie",
    overview:
      "Since the moment they met at age 5, Rosie and Alex have been best friends, facing the highs and lows of growing up side by side. A fleeting shared moment, one missed opportunity, and the decisions that follow send their lives in completely different directions. As each navigates the complexities of life, love, and everything in between, they always find their way back to each other - but is it just friendship, or something more?",
    popularity: 61.133,
    poster_path: "/rpD0t7DhzJVadnzgxSYrqljQTL2.jpg",
    release_date: "2014-10-16",
    title: "Love, Rosie",
    video: false,
    vote_average: 7.8,
    vote_count: 5529,
  },
  {
    adult: false,
    backdrop_path: "/sMAv1YV6bCuy3lnzqXPdrCkIv7e.jpg",
    genre_ids: [18, 12, 28],
    id: 302666,
    original_language: "en",
    original_title: "10.0 Earthquake",
    overview:
      "Los Angeles is about to be hit by a devastating earthquake, and time is running out to save the city from imminent danger.",
    popularity: 58.164,
    poster_path: "/conlM8JWEaHnIPiBqTg7ciiiLLX.jpg",
    release_date: "2014-10-15",
    title: "10.0 Earthquake",
    video: false,
    vote_average: 5,
    vote_count: 95,
  },
  {
    adult: false,
    backdrop_path: "/fRGxZuo7jJUWQsVg9PREb98Aclp.jpg",
    genre_ids: [18, 10402],
    id: 244786,
    original_language: "en",
    original_title: "Whiplash",
    overview:
      "Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.",
    popularity: 56.35,
    poster_path: "/oPxnRhyAIzJKGUEdSiwTJQBa3NM.jpg",
    release_date: "2014-10-10",
    title: "Whiplash",
    video: false,
    vote_average: 8.4,
    vote_count: 12418,
  },
  {
    adult: false,
    backdrop_path: "/mRNU6WHEFqoF9RSVo8o0lpprWil.jpg",
    genre_ids: [53, 28, 878],
    id: 218043,
    original_language: "en",
    original_title: "Left Behind",
    overview:
      "A small group of survivors are left behind after millions of people suddenly vanish during the rapture and the world is plunged into chaos and destruction.",
    popularity: 46.415,
    poster_path: "/b9Q2WR62yB5Aq0hd6kyRFS9cc3Y.jpg",
    release_date: "2014-10-03",
    title: "Left Behind",
    video: false,
    vote_average: 4.2,
    vote_count: 1106,
  },
  {
    adult: false,
    backdrop_path: "/ffc8RVgAWdm3qNtJ5Eq9RKck9Ft.jpg",
    genre_ids: [28, 12, 14, 10770],
    id: 317960,
    original_language: "en",
    original_title: "Viking Quest",
    overview:
      "Erick, a young Viking warrior, joins forces with a rival clan in order to rescue a kidnapped princess from the great Midgard Serpent. It's a perilous task with a risk far greater than merely their own lives; by rescuing the princess, they might cause Ragnarök - the end of the world.",
    popularity: 49.911,
    poster_path: "/grma5z8uPKan8IR4DdtXm1g2BWz.jpg",
    release_date: "2014-10-07",
    title: "Viking Quest",
    video: false,
    vote_average: 4.4,
    vote_count: 27,
  },
  {
    adult: false,
    backdrop_path: "/rTWHdg3FsNTtF5jY2jOhMfjgZz9.jpg",
    genre_ids: [27, 9648, 53],
    id: 297608,
    original_language: "en",
    original_title: "The Taking of Deborah Logan",
    overview:
      "What starts as a poignant medical documentary about Deborah Logan's descent into Alzheimer's disease and her daughter's struggles as caregiver degenerates into a maddening portrayal of dementia at its most frightening, as hair-raising events begin to plague the family and crew and an unspeakable malevolence threatens to tear the very fabric of sanity from them all.",
    popularity: 35.228,
    poster_path: "/77i7EBUyQKOUiZeYQ5tWDGQb0AI.jpg",
    release_date: "2014-10-21",
    title: "The Taking of Deborah Logan",
    video: false,
    vote_average: 6.4,
    vote_count: 917,
  },
  {
    adult: false,
    backdrop_path: "/sETF4vyjb0FonUJVqgrkaPWqiIf.jpg",
    genre_ids: [28],
    id: 289720,
    original_language: "en",
    original_title: "Outcast",
    overview:
      "A mysterious warrior teams up with the daughter and son of a deposed Chinese Emperor to defeat their cruel brother, who seeks their deaths.",
    popularity: 41.461,
    poster_path: "/efsgCTlofzIuysfokEp7hwQnUho.jpg",
    release_date: "2014-09-26",
    title: "Outcast",
    video: false,
    vote_average: 5,
    vote_count: 380,
  },
  {
    adult: false,
    backdrop_path: "/3eceKlZKBcxOgyX2siIhTAI5PFp.jpg",
    genre_ids: [35],
    id: 214758,
    original_language: "es",
    original_title: "Sexo fácil, películas tristes",
    overview:
      "Buenos Aires screenwriter Pablo is hired to write a new romantic comedy. As he begins his story, he visualizes his characters living in Madrid. Pablo creates a meet-cute between Marina and Víctor, a cute couple in Madrid who are soon totally in love. Yet as Pablo gets more and more into the script, he finds it difficult to separate his movie characters from what is happening in his own real life – specifically, his own love life.",
    popularity: 39.785,
    poster_path: "/nYfaC5cI6jpo3NHh15Z2cUrQKsf.jpg",
    release_date: "2014-10-16",
    title: "Easy Sex, Sad Movies",
    video: false,
    vote_average: 5.4,
    vote_count: 51,
  },
  {
    adult: false,
    backdrop_path: "/mXcoOFlpwNepO3TsWGuPb9Aurld.jpg",
    genre_ids: [53, 28, 878],
    id: 312526,
    original_language: "en",
    original_title: "Alien Outpost",
    overview:
      "A documentary crew follows an elite unit of soldiers in the wake of an alien invasion.",
    popularity: 32.717,
    poster_path: "/dXe0HXP66DyTv6mw5pxbGq89knr.jpg",
    release_date: "2014-09-19",
    title: "Alien Outpost",
    video: false,
    vote_average: 5.2,
    vote_count: 185,
  },
  {
    adult: false,
    backdrop_path: "/oIGbatCzX8wU5HGFzGPCa6nLRVy.jpg",
    genre_ids: [18, 27, 53, 9648],
    id: 284303,
    original_language: "de",
    original_title: "Ich seh, Ich seh",
    overview:
      "In the heat of the summer lays a lonesome house in the countryside where nine year old twin brothers await their mother’s return.  When she comes home, bandaged after cosmetic surgery, nothing is like before and the children start to doubt whether this woman is actually who she says she is.",
    popularity: 32.832,
    poster_path: "/u3G2gF7M9dmH4Vcs54PUjieOi0C.jpg",
    release_date: "2014-10-07",
    title: "Goodnight Mommy",
    video: false,
    vote_average: 6.7,
    vote_count: 1263,
  },
  {
    adult: false,
    backdrop_path: "/iTc8GzE4I4v9NLtEQ7ZaUvIj272.jpg",
    genre_ids: [53],
    id: 284427,
    original_language: "de",
    original_title: "Who Am I - Kein System ist sicher",
    overview:
      "Benjamin, a young German computer whiz, is invited to join a subversive hacker group that wants to be noticed on the world's stage.",
    popularity: 29.135,
    poster_path: "/nMHCJiVFjUmQWC116Ze96u5IhfX.jpg",
    release_date: "2014-09-25",
    title: "Who Am I",
    video: false,
    vote_average: 7.7,
    vote_count: 1228,
  },
  {
    adult: false,
    backdrop_path: "/zY75ms36ypIQxFAFLtoYfNFuSD7.jpg",
    genre_ids: [35, 10749],
    id: 277547,
    original_language: "en",
    original_title: "Playing It Cool",
    overview:
      "A young man meets and instantly falls in love with an engaged woman.",
    popularity: 34.271,
    poster_path: "/96htqghZlKctNJqDLo2DuC9PEap.jpg",
    release_date: "2014-09-26",
    title: "Playing It Cool",
    video: false,
    vote_average: 5.9,
    vote_count: 655,
  },
];

// https://api.themoviedb.org/3/discover/movie?primary_release_date.gte=2014-09-15&primary_release_date.lte=2014-10-22&api_key=fcc651f2e319bf0891036e2b83989afc
